[package]
name = "rustbridge"
version = "0.1.0"
authors = ["Sílvia Mur Blanch <pchiwan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "0.2.0"